### ISSUE TITLE
Doesn't appear to be working 

### ISSUE THREAD

**Issue by iron-man** [joshmcarthur/mail-logger#1]
I installed this on a rails 4.0.1 and ruby 2.0.0 install and it creates the mail_development.log file, and I have it configured to send emails in the config, and I get the emails, and I can see that they were sent in the development.log file, but the mail_development.log file that this gem creates remains empty.  I can't see why that would be the case.

**Comment by joshmcarthur** [comment]
Sorry about that. I've just created a test application and managed to replicate the issue you had. Just to check though, do you have output in your log file after your process exits? For example, when I open a Rails console and send an email, I don't see the email in the log immediately - I see it after I type `exit` in the Rails console.

It turns out that this is due to the way that Ruby's `Logger` class works - it doesn't necessarily flush the new log lines right away. I'm looking at the best way to have the file write more frequently right now, so I'll update if my changes result in a new release.

**Comment by joshmcarthur** [comment]
According to the [`IO` Documentation](http://www.ruby-doc.org/core-2.1.1/IO.html#method-i-sync-3D) (which is ultimately what the `File` object attached to the `Logger` uses, manually telling the logfile to sync all the time may have performance implications. Because of this, I plan on introducing ActiveSupport to that I can use their `BufferedLogger` implementation.

**Comment by joshmcarthur** [comment]
@iron-man I have just released [version 0.0.3](http://rubygems.org/gems/mail-logger/versions/0.0.3) to Rubygems. Please try it out and see if this fixes your issue.

**Comment by iron-man** [comment]
Thanks for looking at this so quick!  I was seeing the same thing, with the logs not being filled in, and randomly, I checked later and they had some logs, which now you mention it, I did restart the server, so that makes sense.  I've updated my version of the mail-logger, and it appears to be working better on my local dev box.  I'll take a look at my dev server and see if that is doing better too.

**Comment by joshmcarthur** [comment]
Great to hear!

I'll close this issue now - please re-open if you still see the problem.
